USE [Flashcards]
GO

/****** Object:  Table [dbo].[Flashcards]    Script Date: 1/12/2023 10:28:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Flashcards](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Question] [text] NOT NULL,
	[Answer] [text] NOT NULL,
	[StackId] [int] NULL,
	[Stackname] [text] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[Flashcards]  WITH CHECK ADD FOREIGN KEY([StackId])
REFERENCES [dbo].[Stacks] ([Id])
GO

ALTER TABLE [dbo].[Flashcards]  WITH CHECK ADD  CONSTRAINT [FK_StackId] FOREIGN KEY([StackId])
REFERENCES [dbo].[Stacks] ([Id])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Flashcards] CHECK CONSTRAINT [FK_StackId]
GO

