// <auto-generated />
using System;
using Flashcards.TwilightSaw.Controller;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flashcards.TwilightSaw.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241111153144_Create")]
    partial class Create
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Flashcards.TwilightSaw.Models.CardStack", b =>
                {
                    b.Property<int>("CardStackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardStackId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CardStackId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CardStacks");
                });

            modelBuilder.Entity("Flashcards.TwilightSaw.Models.Flashcard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Back")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CardStackId")
                        .HasColumnType("int");

                    b.Property<string>("Front")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CardStackId");

                    b.ToTable("Flashcards");
                });

            modelBuilder.Entity("Flashcards.TwilightSaw.Models.StudySession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CardStackId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardStackId");

                    b.ToTable("StudySessions");
                });

            modelBuilder.Entity("Flashcards.TwilightSaw.Models.Flashcard", b =>
                {
                    b.HasOne("Flashcards.TwilightSaw.Models.CardStack", "CardStack")
                        .WithMany("Flashcards")
                        .HasForeignKey("CardStackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardStack");
                });

            modelBuilder.Entity("Flashcards.TwilightSaw.Models.StudySession", b =>
                {
                    b.HasOne("Flashcards.TwilightSaw.Models.CardStack", "CardStack")
                        .WithMany("Sessions")
                        .HasForeignKey("CardStackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardStack");
                });

            modelBuilder.Entity("Flashcards.TwilightSaw.Models.CardStack", b =>
                {
                    b.Navigation("Flashcards");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
