graph TD
    Flashcards.RyanW84[Flashcards.RyanW84]
    Flashcards.RyanW84-->Flashcards.RyanW84Models[Models]
    Flashcards.RyanW84Models-->Flashcards.RyanW84ModelsDTO[DTO]
    Flashcards.RyanW84ModelsDTO-->Flashcards.RyanW84ModelsDTOStudySessionDTO.cs((StudySessionDTO.cs))
    Flashcards.RyanW84ModelsDTOStudySessionDTO.cs-->|class|Flashcards.RyanW84ModelsDTOStudySessionDTO.csStudySessionDTO[StudySessionDTO]
    Flashcards.RyanW84Models-->Flashcards.RyanW84ModelsFlashcard.cs((Flashcard.cs))
    Flashcards.RyanW84ModelsFlashcard.cs-->|class|Flashcards.RyanW84ModelsFlashcard.csFlashcard[Flashcard]
    Flashcards.RyanW84Models-->Flashcards.RyanW84ModelsStack.cs((Stack.cs))
    Flashcards.RyanW84ModelsStack.cs-->|class|Flashcards.RyanW84ModelsStack.csStack[Stack]
    Flashcards.RyanW84Models-->Flashcards.RyanW84ModelsStudySession.cs((StudySession.cs))
    Flashcards.RyanW84ModelsStudySession.cs-->|class|Flashcards.RyanW84ModelsStudySession.csStudySession[StudySession]
    Flashcards.RyanW84-->Flashcards.RyanW84DataAccess.cs((DataAccess.cs))
    Flashcards.RyanW84DataAccess.cs-->|class|Flashcards.RyanW84DataAccess.csDataAccess[DataAccess]
    Flashcards.RyanW84DataAccess.csDataAccess-->|method|Flashcards.RyanW84DataAccess.csDataAccessConfirmConnection(ConfirmConnection)
    Flashcards.RyanW84DataAccess.csDataAccess-->|method|Flashcards.RyanW84DataAccess.csDataAccessCreateTables(CreateTables)
    Flashcards.RyanW84DataAccess.csDataAccess-->|method|Flashcards.RyanW84DataAccess.csDataAccessGetAllStacks(GetAllStacks)
    Flashcards.RyanW84DataAccess.csDataAccess-->|method|Flashcards.RyanW84DataAccess.csDataAccessBulkInsertRecords(BulkInsertRecords)
    Flashcards.RyanW84DataAccess.csDataAccess-->|method|Flashcards.RyanW84DataAccess.csDataAccessInsertStack(InsertStack)
    Flashcards.RyanW84DataAccess.csDataAccess-->|method|Flashcards.RyanW84DataAccess.csDataAccessDeleteStack(DeleteStack)
    Flashcards.RyanW84DataAccess.csDataAccess-->|method|Flashcards.RyanW84DataAccess.csDataAccessUpdateStack(UpdateStack)
    Flashcards.RyanW84DataAccess.csDataAccess-->|method|Flashcards.RyanW84DataAccess.csDataAccessGetFlashcards(GetFlashcards)
    Flashcards.RyanW84DataAccess.csDataAccess-->|method|Flashcards.RyanW84DataAccess.csDataAccessInsertFlashcard(InsertFlashcard)
    Flashcards.RyanW84DataAccess.csDataAccess-->|method|Flashcards.RyanW84DataAccess.csDataAccessDeleteFlashcard(DeleteFlashcard)
    Flashcards.RyanW84DataAccess.csDataAccess-->|method|Flashcards.RyanW84DataAccess.csDataAccessUpdateFlashcard(UpdateFlashcard)
    Flashcards.RyanW84DataAccess.csDataAccess-->|method|Flashcards.RyanW84DataAccess.csDataAccessInsertStudySession(InsertStudySession)
    Flashcards.RyanW84DataAccess.csDataAccess-->|method|Flashcards.RyanW84DataAccess.csDataAccessGetStudySessionData(GetStudySessionData)
    Flashcards.RyanW84-->Flashcards.RyanW84Enums.cs((Enums.cs))
    Flashcards.RyanW84Enums.cs-->|class|Flashcards.RyanW84Enums.csEnums[Enums]
    Flashcards.RyanW84-->Flashcards.RyanW84Program.cs((Program.cs))
    Flashcards.RyanW84-->Flashcards.RyanW84SeedData.cs((SeedData.cs))
    Flashcards.RyanW84SeedData.cs-->|class|Flashcards.RyanW84SeedData.csSeedData[SeedData]
    Flashcards.RyanW84SeedData.csSeedData-->|method|Flashcards.RyanW84SeedData.csSeedDataSeedRecords(SeedRecords)
    Flashcards.RyanW84-->Flashcards.RyanW84UserInterface.cs((UserInterface.cs))
    Flashcards.RyanW84UserInterface.cs-->|class|Flashcards.RyanW84UserInterface.csUserInterface[UserInterface]
    Flashcards.RyanW84UserInterface.csUserInterface-->|method|Flashcards.RyanW84UserInterface.csUserInterfaceGetEnumDisplayName(GetEnumDisplayName)
    Flashcards.RyanW84UserInterface.csUserInterface-->|method|Flashcards.RyanW84UserInterface.csUserInterfaceMainMenu(MainMenu)
    Flashcards.RyanW84UserInterface.csUserInterface-->|method|Flashcards.RyanW84UserInterface.csUserInterfaceStacksMenu(StacksMenu)
    Flashcards.RyanW84UserInterface.csUserInterface-->|method|Flashcards.RyanW84UserInterface.csUserInterfaceFlashcardsMenu(FlashcardsMenu)
    Flashcards.RyanW84UserInterface.csUserInterface-->|method|Flashcards.RyanW84UserInterface.csUserInterfaceChooseStack(ChooseStack)
    Flashcards.RyanW84UserInterface.csUserInterface-->|method|Flashcards.RyanW84UserInterface.csUserInterfaceViewStacks(ViewStacks)
    Flashcards.RyanW84UserInterface.csUserInterface-->|method|Flashcards.RyanW84UserInterface.csUserInterfaceAddStack(AddStack)
    Flashcards.RyanW84UserInterface.csUserInterface-->|method|Flashcards.RyanW84UserInterface.csUserInterfaceDeleteStack(DeleteStack)
    Flashcards.RyanW84UserInterface.csUserInterface-->|method|Flashcards.RyanW84UserInterface.csUserInterfaceUpdateStack(UpdateStack)
    Flashcards.RyanW84UserInterface.csUserInterface-->|method|Flashcards.RyanW84UserInterface.csUserInterfaceChooseFlashcard(ChooseFlashcard)
    Flashcards.RyanW84UserInterface.csUserInterface-->|method|Flashcards.RyanW84UserInterface.csUserInterfaceViewFlashcards(ViewFlashcards)
    Flashcards.RyanW84UserInterface.csUserInterface-->|method|Flashcards.RyanW84UserInterface.csUserInterfaceAddFlashcard(AddFlashcard)
    Flashcards.RyanW84UserInterface.csUserInterface-->|method|Flashcards.RyanW84UserInterface.csUserInterfaceDeleteFlashcard(DeleteFlashcard)
    Flashcards.RyanW84UserInterface.csUserInterface-->|method|Flashcards.RyanW84UserInterface.csUserInterfaceGetQuestion(GetQuestion)
    Flashcards.RyanW84UserInterface.csUserInterface-->|method|Flashcards.RyanW84UserInterface.csUserInterfaceGetAnswer(GetAnswer)
    Flashcards.RyanW84UserInterface.csUserInterface-->|method|Flashcards.RyanW84UserInterface.csUserInterfaceUpdateFlashcard(UpdateFlashcard)
    Flashcards.RyanW84UserInterface.csUserInterface-->|method|Flashcards.RyanW84UserInterface.csUserInterfaceStudySession(StudySession)
    Flashcards.RyanW84UserInterface.csUserInterface-->|method|Flashcards.RyanW84UserInterface.csUserInterfaceViewStudyHistory(ViewStudyHistory)
